name: heart_pick
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.17
  flutter_screenutil: ^5.9.3
  json_annotation: ^4.9.0
  freezed_annotation: ^2.2.0
  dio: ^5.8.0+1
  either_dart: ^0.3.0
  get_it: ^8.0.3
  flutter_bloc: ^9.0.0

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  build_runner: ^2.3.0
  json_serializable: ^6.5.4
  freezed: ^2.3.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/


  fonts:
    - family: Mariupol-Bold
      fonts:
        - asset: fonts/Mariupol-Bold.ttf
          weight: 700



